# Generated by Django 4.1.5 on 2023-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kinetics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solutiondata",
            name="error_exp_point",
            field=models.TextField(default=None, verbose_name="Погрешность в эксп. точках"),
        ),
    ]
