# Generated by Django 4.1.5 on 2023-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kinetics", "0003_alter_inputdata_initial_time_alter_inputdata_step_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitivityResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("average", models.TextField(verbose_name="Среднее значение")),
                ("absolute_average", models.TextField(verbose_name="Абсолютное среднее значение")),
                ("standart_deviation", models.TextField(verbose_name="Стандартное отклонение")),
                ("constant_speed_num", models.TextField(verbose_name="Нумерация констант скорости")),
            ],
            options={
                "verbose_name": "Sensitivity Result",
            },
        ),
    ]
