# Generated by Django 4.1.5 on 2023-05-09 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kinetics", "0003_alter_solutiondata_error_exp_point"),
        ("kinetics", "0004_sensitivityresult"),
    ]

    operations = []
