# Generated by Django 4.1.5 on 2023-05-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kinetics", "0004_sensitivityresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="solutiondata",
            name="runtime",
            field=models.FloatField(default=None, verbose_name="Время выполнения"),
        ),
    ]
