# Generated by Django 4.1.5 on 2023-05-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kinetics", "0005_merge_20230509_2111"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensitivityresult",
            name="time",
            field=models.TextField(default=None, verbose_name="Время"),
        ),
    ]
