# Generated by Django 4.1.5 on 2023-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_time', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Начальное время t0')),
                ('time', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Время t')),
                ('step', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Шаг')),
                ('matrix_stechiometric_coefficients', models.JSONField(verbose_name='Матрица стехиометрических коэффициентов')),
                ('matrix_indicators', models.JSONField(verbose_name='Матрица показателей степени')),
                ('experimental_data', models.JSONField(verbose_name='Экспериментальные данные')),
                ('constants_speed', models.JSONField(verbose_name='Константы скорости')),
                ('method', models.CharField(choices=[('EULER', 'Метод Эйлера'), ('IMPLICIT_EULER', 'Неявный метод Эйлера'), ('TRAPEZOID', 'Метод трапеций'), ('MIDDLE', 'Метод средней точки'), ('RK2', 'Метод Рунге-Кутты 2-го порядка'), ('RK4', 'Метод Рунге-Кутты 4-го порядка'), ('KM', 'Метод Кутты-Мерсона'), ('RKF', 'Метод Рунге-Кутты-Фелберга'), ('EXPLICIT_ADAMS', 'Явный двухшаговый метод Адамса')], default='EULER', max_length=255, verbose_name='Метод решения')),
            ],
        ),
        migrations.CreateModel(
            name='TableParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.IntegerField(verbose_name='Количество компонентов')),
                ('stages', models.IntegerField(verbose_name='Количество стадий')),
                ('experiments', models.IntegerField(verbose_name='Количество экспериментов')),
            ],
        ),
    ]
