# Generated by Django 4.1.5 on 2023-01-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='constants_speed',
            field=models.TextField(verbose_name='Константы скорости'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='experimental_data',
            field=models.TextField(verbose_name='Экспериментальные данные'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='matrix_indicators',
            field=models.TextField(verbose_name='Матрица показателей степени'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='matrix_stechiometric_coefficients',
            field=models.TextField(verbose_name='Матрица стехиометрических коэффициентов'),
        ),
        migrations.CreateModel(
            name='SolutionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(verbose_name='Данные, расчитанные выбранным методом')),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinetics.inputdata', verbose_name='Входные данные')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
