# Generated by Django 4.1.5 on 2023-01-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0002_alter_inputdata_constants_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='method',
            field=models.CharField(max_length=255, verbose_name='Метод решения'),
        ),
    ]
