# Generated by Django 4.1.5 on 2023-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0003_alter_inputdata_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='method',
            field=models.CharField(choices=[('EULER', 'Метод Эйлера'), ('IMPLICIT_EULER', 'Неявный метод Эйлера'), ('TRAPEZOID', 'Метод трапеций'), ('MIDDLE', 'Метод средней точки'), ('RK2', 'Метод Рунге-Кутты 2-го порядка'), ('RK4', 'Метод Рунге-Кутты 4-го порядка'), ('KM', 'Метод Кутты-Мерсона'), ('RKF', 'Метод Рунге-Кутты-Фелберга'), ('EXPLICIT_ADAMS', 'Явный двухшаговый метод Адамса')], default='EULER', max_length=255, verbose_name='Метод решения'),
        ),
    ]
