# Generated by Django 4.1.5 on 2023-01-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0004_alter_inputdata_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='initial_time',
            field=models.FloatField(verbose_name='Начальное время t0'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='step',
            field=models.FloatField(verbose_name='Шаг'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='time',
            field=models.FloatField(verbose_name='Время t'),
        ),
    ]
