# Generated by Django 4.1.5 on 2023-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0006_solutiondata_time_alter_solutiondata_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solutiondata',
            options={},
        ),
        migrations.AlterField(
            model_name='solutiondata',
            name='time',
            field=models.TextField(verbose_name='Время'),
        ),
    ]
