# Generated by Django 4.1.5 on 2023-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0008_solutiondata_experimental_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutiondata',
            name='experimental_point',
            field=models.TextField(verbose_name='Значение в эксп. точках'),
        ),
    ]
