# Generated by Django 4.1.5 on 2023-02-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0010_inputdata_table_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='table_parameters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinetics.tableparameters', verbose_name='Параметры таблицы'),
        ),
    ]
